max_path_length_m: 6.853
spawn_x: -0.5
spawn_y: 0.4
rows:
- id: 1
  y: 0.4
  west_x: 0.3
  east_x: 5.7
- id: 2
  y: 1.4
  west_x: 0.3
  east_x: 5.7
- id: 3
  y: 2.4
  west_x: 0.3
  east_x: 5.7
- id: 4
  y: 3.4
  west_x: 0.3
  east_x: 5.7
