max_path_length_m: 7.083
rows:
- id: 1
  waypoints:
  - x: 0.3
    y: 0.5
    yaw: 0.0
  - x: 5.7
    y: 0.5
    yaw: 0.0
- id: 2
  waypoints:
  - x: 5.7
    y: 1.9
    yaw: 3.14159
  - x: 0.3
    y: 1.9
    yaw: 3.14159
- id: 3
  waypoints:
  - x: 0.3
    y: 3.3
    yaw: 0.0
  - x: 5.7
    y: 3.3
    yaw: 0.0
- id: 4
  waypoints:
  - x: 5.7
    y: 4.7
    yaw: 3.14159
  - x: 0.3
    y: 4.7
    yaw: 3.14159
- id: 5
  waypoints:
  - x: 0.3
    y: 6.1
    yaw: 0.0
  - x: 5.7
    y: 6.1
    yaw: 0.0
